"""Closed-form correctness tests for the pure-NumPy information-theoretic estimators.

Every assertion here compares a computed number against a value known
*independently* of the implementation (an analytic formula for the generating
process, or an information-theoretic inequality). This is the only place in the
suite where a ``return np.zeros(...)`` stub would be caught: the rest of the
tests check shape/finiteness or compare against a baseline generated by the same
code.

LOG BASE: every estimator in the module reports **nats**. The kernel and
symbolic calculators used to report bits, inherited from JIDT's split between
base 2 for its box-kernel/discrete estimators and base e for its Gaussian and
k-nearest-neighbour ones. `_expected` and `BITS_ESTIMATORS` survive as the
place a future base-2 estimator would have to declare itself, rather than
silently landing on an axis differing by a factor of ln 2.

Sampling: the Gaussian fixtures are whitened so the *sample* covariance equals
the target covariance exactly. Expectations are therefore computed from the
known rho of the generating process, never from ``np.corrcoef`` of the sample —
comparing against the sample correlation would reduce the Gaussian test to an
implementation identity that cannot detect a wrong rho or a wrong log base.
Whitening also removes the O(1/sqrt(N)) sampling noise in rho, which is what
lets the Gaussian tolerance be 1e-7 rather than 1e-2. Not tighter:
the Gaussian path ridge-regularises the covariance at 1e-8 relative
(the deterministic analogue of JIDT's NOISE_LEVEL_TO_ADD), so identities
assembled from several entropies cannot cancel below that order. The
previous 1e-9 passed only because the vectorised multivariate path
skipped the ridge, which is exactly the inconsistency that made
bivariate() and multivariate() disagree by 8.4 nats on singular data.
"""
import numpy as np
import pytest

from pyspi.data import Data
from pyspi.statistics.infotheory import (
    CausalEntropy,
    ConditionalEntropy,
    CrossmapEntropy,
    DirectedInfo,
    GaussianEntropyCalculator,
    JointEntropy,
    KLEntropyCalculator,
    KernelEntropyCalculator,
    MutualInfo,
    StochasticInteraction,
    TimeLaggedMutualInfo,
    TransferEntropy,
)

# Every estimator in the module reports nats; see InfoTheoryBase.
BITS_ESTIMATORS = frozenset()

N_LARGE = 20000
N_SMALL = 3000

# Per-estimator absolute tolerances against the analytic MI, in that
# estimator's own units. Gaussian is a closed form on an exactly-specified
# covariance, so it is held to round-off. The kNN and box-kernel estimators
# carry genuine O(1e-2) finite-sample bias at N=20000 (KSG k=4; box kernel at
# fixed bandwidth 0.25) — these are estimator properties, not slack chosen to
# make the test pass; the measured errors are ~0.009.
# 1e-7, not 1e-9: the Gaussian MI path now goes through the same ridge as
# the entropy path, which biases it by ridge*r^2/(1-r^2) ~ 5.6e-9 at
# rho=0.6. That is the price of the two paths agreeing at r -> 1, where
# they used to differ by 8.4 nats.
MI_ATOL = {"gaussian": 1e-7, "kraskov": 0.02, "kernel": 0.02, "kozachenko": 0.02}

_ESTIMATOR_KWARGS = {"kraskov": {"prop_k": 4}, "kernel": {"kernel_width": 0.25}}

# kozachenko is deliberately absent: MutualInfo and TimeLaggedMutualInfo are
# estimated directly rather than from marginal entropies, and there is no
# Kozachenko-Leonenko path for them. The constructor now raises, so the
# combination is rejected rather than tested -- see
# test_smoke.test_kozachenko_rejected_for_non_entropy.
MI_ESTIMATORS = [
    "gaussian",
    "kraskov",
    "kernel",
    pytest.param("_removed_kozachenko", marks=pytest.mark.skip(
        reason="rejected at construction; see test_kozachenko_rejected_for_non_entropy",
    )),
]


def _expected(value_in_nats, estimator):
    """Analytic values need no conversion: the whole module reports nats.

    Kept as a function, and `BITS_ESTIMATORS` kept as an (empty) set, so that
    reintroducing a base-2 estimator has an obvious place to declare itself
    rather than silently landing on an axis differing by ln 2.
    """
    return value_in_nats / np.log(2) if estimator in BITS_ESTIMATORS else value_in_nats


def _spi(cls, estimator, **kwargs):
    return cls(estimator=estimator, **_ESTIMATOR_KWARGS.get(estimator, {}), **kwargs)


def _exact_gaussian_pair(rho, n=N_LARGE, seed=0):
    """Bivariate normal whose *sample* covariance is exactly [[1, rho], [rho, 1]]."""
    rng = np.random.default_rng(seed)
    Z = rng.standard_normal((2, n))
    Z = Z - Z.mean(axis=1, keepdims=True)
    Z = np.linalg.inv(np.linalg.cholesky(np.cov(Z, ddof=1))) @ Z
    return np.linalg.cholesky(np.array([[1.0, rho], [rho, 1.0]])) @ Z


def _ar1_with_drive(a, b, sigma=1.0, n=N_LARGE, seed=0):
    """y_t = a*y_{t-1} + b*x_{t-1} + sigma*eps_t, with x iid N(0, 1)."""
    rng = np.random.default_rng(seed)
    x = rng.standard_normal(n)
    eps = rng.standard_normal(n)
    y = np.zeros(n)
    for t in range(1, n):
        y[t] = a * y[t - 1] + b * x[t - 1] + sigma * eps[t]
    return np.vstack([x, y])


def _coupled_pair(coupling, n=N_SMALL, seed=0):
    """X -> Y at lag 1 with strength ``coupling`` (0 gives independent series)."""
    rng = np.random.default_rng(seed)
    x = rng.standard_normal(n)
    y = np.zeros(n)
    for t in range(1, n):
        y[t] = 0.5 * y[t - 1] + coupling * x[t - 1] + rng.standard_normal()
    return np.vstack([x, y])


# ---------------------------------------------------------------------------
# Mutual information against the exact bivariate-Gaussian value
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("estimator", MI_ESTIMATORS)
@pytest.mark.parametrize("rho", [0.0, 0.3, 0.6, 0.9])
def test_bivariate_gaussian_mi(estimator, rho):
    """MI of a bivariate normal is exactly -0.5*ln(1 - rho^2) nats."""
    data = Data(_exact_gaussian_pair(rho), zscore=False)
    result = _spi(MutualInfo, estimator).multivariate(data)

    assert result.shape == (2, 2)
    assert np.all(np.isnan(np.diag(result))), "diagonal must be NaN"

    expected = _expected(-0.5 * np.log(1.0 - rho ** 2), estimator)
    assert result[0, 1] == pytest.approx(result[1, 0], abs=1e-12), "MI must be symmetric"
    assert result[0, 1] == pytest.approx(expected, abs=MI_ATOL[estimator]), (
        f"{estimator} MI at rho={rho}: got {result[0, 1]}, expected {expected}"
    )


# ---------------------------------------------------------------------------
# Differential entropy of N(0, sigma^2)
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("sigma", [1.0, 2.0])
@pytest.mark.parametrize("estimator", ["gaussian", "kozachenko", "kernel"])
def test_gaussian_differential_entropy(estimator, sigma):
    """H[N(0, sigma^2)] = 0.5*ln(2*pi*e*sigma^2) nats.

    Exercises the entropy calculators directly rather than through a SPI,
    because Data() z-scores by default and would destroy sigma.
    """
    rng = np.random.default_rng(7)
    x = sigma * rng.standard_normal(N_LARGE)

    calc = {
        "gaussian": GaussianEntropyCalculator,
        "kozachenko": KLEntropyCalculator,
        "kernel": KernelEntropyCalculator,
    }[estimator]()
    calc.initialise(1)
    if estimator == "kernel":
        calc.setProperty("KERNEL_WIDTH", "0.25")
    calc.setObservations(x)
    got = calc.computeAverageLocalOfObservations()

    expected = _expected(0.5 * np.log(2 * np.pi * np.e * sigma ** 2), estimator)
    # Absolute, in the estimator's own units. All three are consistent (mean
    # error -> 0 with N) but noisy at finite N: the Kozachenko-Leonenko k=1
    # estimator has sd ~0.013 nats at N=20000, measured over 15 seeds, and the
    # box kernel carries a small bandwidth-dependent bias. 0.05 is ~4 sd, and
    # still 14x tighter than ln(2)=0.693 — the smallest error a wrong log base
    # or a dropped normalisation constant could produce.
    assert got == pytest.approx(expected, abs=0.05), (
        f"{estimator} H[N(0,{sigma}^2)]: got {got}, expected {expected}"
    )


# ---------------------------------------------------------------------------
# Gaussian transfer entropy on a known AR(1)-with-drive process
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("a, b", [(0.5, 0.6), (0.2, 0.9), (0.7, 0.3)])
def test_gaussian_te_ar1_analytic(a, b):
    """TE(X->Y) = 0.5*ln(var_reduced / var_full) for y_t = a y_{t-1} + b x_{t-1} + eps.

    x is iid and independent of y_{t-1}, so conditioning on y_{t-1} alone leaves
    residual variance b^2 var(x) + sigma^2, while conditioning on (y_{t-1},
    x_{t-1}) leaves sigma^2. TE(Y->X) is 0 because x has no history at all.
    """
    sigma = 1.0
    data = Data(_ar1_with_drive(a, b, sigma), zscore=True)
    result = TransferEntropy(estimator="gaussian").multivariate(data)

    expected = 0.5 * np.log((b ** 2 * 1.0 + sigma ** 2) / sigma ** 2)
    assert result[0, 1] == pytest.approx(expected, abs=0.01), (
        f"TE(X->Y): got {result[0, 1]}, expected {expected}"
    )
    assert abs(result[1, 0]) < 0.01, f"TE(Y->X) should vanish, got {result[1, 0]}"


# ---------------------------------------------------------------------------
# Independence: everything must collapse to ~0
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("cls", [MutualInfo, TimeLaggedMutualInfo, TransferEntropy])
@pytest.mark.parametrize("estimator", ["gaussian", "kraskov", "kernel"])
def test_independent_series_give_near_zero(cls, estimator):
    """X independent of Y => MI, TLMI and TE are ~0 for every estimator.

    This is the assertion a constant-returning stub cannot survive; `isfinite`
    checks elsewhere in the suite would pass one.

    The box-kernel TE is the one exception: at fixed bandwidth in the 3-D
    (y_next, y_past, x_past) space it carries a large positive finite-sample
    bias (~0.06 nats at N=10000, decaying with N). That is an estimator
    property, documented rather than hidden — the bias is still an order of
    magnitude below the coupled value, which is what
    ``test_coupling_increases_directed_measures`` checks.
    """
    data = Data(_coupled_pair(0.0, n=10000), zscore=True)
    result = _spi(cls, estimator).multivariate(data)
    off_diagonal = result[~np.isnan(result)]

    limit = 0.15 if (cls is TransferEntropy and estimator == "kernel") else 0.05
    assert np.max(np.abs(off_diagonal)) < limit, (
        f"{cls.__name__}/{estimator} on independent series: {result}"
    )


def test_symbolic_te_independent_series():
    """Symbolic TE (histogram-based) also collapses on independent data."""
    data = Data(_coupled_pair(0.0, n=10000), zscore=True)
    result = TransferEntropy(estimator="symbolic", k_history=3).multivariate(data)
    assert np.max(np.abs(result[~np.isnan(result)])) < 0.05, result


# ---------------------------------------------------------------------------
# Information-theoretic identities and inequalities
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("estimator", ["gaussian", "kraskov", "kernel"])
def test_nonnegativity_of_mi_and_te(estimator):
    """MI >= 0 and TE >= 0 on real data (small negative estimator noise allowed)."""
    data = Data(_coupled_pair(0.8), zscore=True)
    for cls in (MutualInfo, TimeLaggedMutualInfo, TransferEntropy):
        result = _spi(cls, estimator).multivariate(data)
        worst = np.nanmin(result)
        assert worst > -0.05, f"{cls.__name__}/{estimator} strongly negative: {worst}"


# Tolerance for the entropy-derived MI identity, in each estimator's units.
# gaussian is a closed form (exact). The others are held to a bias/variance
# budget measured over seeds: KL k=1 marginal+joint errors compound to ~0.04
# nats at N=20000; the box kernel to ~0.02 nats.
ENTROPY_MI_ATOL = {"gaussian": 1e-7, "kozachenko": 0.08, "kernel": 0.05}


@pytest.mark.parametrize("estimator", ["gaussian", "kozachenko", "kernel"])
@pytest.mark.parametrize("rho", [0.0, 0.6])
def test_joint_entropy_subadditivity(estimator, rho):
    """H(X) + H(Y) - H(X,Y) must equal the analytic MI, hence be >= 0.

    Marginals are recovered from the public API alone:
    ``ConditionalEntropy[i, j] = H(X_i, X_j) - H(X_i)``, so ``H(X_i) = JE - CE[i, j]``.
    This is the only test that pins JointEntropy and ConditionalEntropy to a
    closed form; everything else only checks that they are finite.

    NOTE: the textbook bound H(X,Y) >= max(H(X), H(Y)) is a *discrete*-entropy
    property and is false for differential entropy — H(Y|X) = 0.5*ln(2*pi*e*
    (1-r^2)) goes negative for |r| large — so it is asserted only at rho=0,
    where it does hold. Subadditivity (equivalently MI >= 0) is always true and
    is asserted at both rho.
    """
    data = Data(_exact_gaussian_pair(rho), zscore=False)
    je = _spi(JointEntropy, estimator).multivariate(data)[0, 1]
    ce = _spi(ConditionalEntropy, estimator).multivariate(data)
    h_x = je - ce[0, 1]
    h_y = je - ce[1, 0]
    mi_from_entropies = h_x + h_y - je

    expected = _expected(-0.5 * np.log(1.0 - rho ** 2), estimator)
    atol = ENTROPY_MI_ATOL[estimator]
    assert mi_from_entropies == pytest.approx(expected, abs=atol), (
        f"{estimator} at rho={rho}: H(X)+H(Y)-H(X,Y)={mi_from_entropies}, "
        f"expected {expected} (H(X)={h_x}, H(Y)={h_y}, H(X,Y)={je})"
    )
    assert mi_from_entropies > -atol, "subadditivity violated beyond estimator noise"
    if rho == 0.0:
        assert je >= max(h_x, h_y) - atol, (
            f"{estimator}: H(X,Y)={je} below max marginal {max(h_x, h_y)}"
        )


def test_mutual_info_chain_rule_gaussian():
    """I(X;Y) = H(X) - H(X|Y), cross-checking MutualInfo against JE/CE.

    Using the identity above for the marginals this becomes
    ``MI = JE - CE[i, j] - CE[j, i]``. Restricted to the gaussian estimator: it
    is the only one where MI and the entropies come from the same closed form,
    so the identity must hold to round-off. The kernel MI uses a different
    (count-ratio) estimator than the kernel entropies, so no exact identity is
    expected there.
    """
    data = Data(_exact_gaussian_pair(0.6), zscore=False)
    mi = MutualInfo(estimator="gaussian").multivariate(data)[0, 1]
    je = JointEntropy(estimator="gaussian").multivariate(data)[0, 1]
    ce = ConditionalEntropy(estimator="gaussian").multivariate(data)

    assert mi == pytest.approx(je - ce[0, 1] - ce[1, 0], abs=1e-7)
    assert mi == pytest.approx(-0.5 * np.log(1 - 0.6 ** 2), abs=1e-7)


# ---------------------------------------------------------------------------
# The five SPI classes that the rest of the suite instantiates but never computes
# ---------------------------------------------------------------------------

# (class, kwargs, sign) — sign is +1 when coupling should *increase* the
# statistic and -1 when it should decrease it. CrossmapEntropy and CausalEntropy
# are conditional entropies: coupling makes the target more predictable, so they
# go DOWN. Asserting "coupled > independent" for them would be backwards.
NEVER_COMPUTED = [
    (TimeLaggedMutualInfo, {}, +1),
    (CrossmapEntropy, {"history_length": 3}, -1),
    (CausalEntropy, {"n": 3}, -1),
    (DirectedInfo, {"n": 3}, +1),
    (StochasticInteraction, {}, +1),
]


@pytest.mark.parametrize("cls, kwargs, sign",
                         NEVER_COMPUTED,
                         ids=[c.__name__ for c, _, _ in NEVER_COMPUTED])
@pytest.mark.parametrize("estimator", ["gaussian", "kozachenko", "kernel"])
def test_coupling_increases_directed_measures(cls, kwargs, sign, estimator):
    # TimeLaggedMutualInfo is estimated directly, not from marginal entropies,
    # so it has no Kozachenko-Leonenko path and rejects the estimator at
    # construction (pinned in test_smoke).
    if estimator == "kozachenko" and cls.__name__ == "TimeLaggedMutualInfo":
        pytest.skip("rejected at construction; see test_kozachenko_rejected_for_non_entropy")
    """Each measure must separate a coupled pair from an independent one."""
    if cls is TimeLaggedMutualInfo and estimator == "kozachenko":
        pytest.xfail("TimeLaggedMutualInfo has no kozachenko path; returns NaN")

    coupled = _spi(cls, estimator, **kwargs).multivariate(
        Data(_coupled_pair(0.8, seed=0), zscore=True))
    independent = _spi(cls, estimator, **kwargs).multivariate(
        Data(_coupled_pair(0.0, seed=0), zscore=True))

    assert np.isfinite(coupled[0, 1]) and np.isfinite(independent[0, 1]), (
        f"{cls.__name__}/{estimator} returned non-finite values"
    )
    delta = sign * (coupled[0, 1] - independent[0, 1])
    assert delta > 0.05, (
        f"{cls.__name__}/{estimator}: coupling did not move the statistic in the "
        f"expected direction (coupled={coupled[0, 1]}, "
        f"independent={independent[0, 1]}, expected sign={sign:+d})"
    )


def test_gaussian_singularity_policy_is_shared_by_every_path():
    """One ridge, reachable from either direction, on exactly singular input.

    Gaussian MI used to clip r^2 at 1 - 1e-15 while the entropy path ridged the
    covariance at 1e-8 relative. On a pair of identical N=100 series the direct
    MI was 17.2698 nats and the same quantity assembled from entropies was
    8.8638 -- a factor of two apart, from two regularisation policies in one
    module. Both now return the ridge's bound, -0.5*log(1 - 1/(1+1e-8)^2).
    """
    from pyspi.statistics.infotheory import GAUSSIAN_RIDGE

    rng = np.random.default_rng(0)
    x = rng.standard_normal(100)
    data = Data(data=np.vstack([x, x.copy()]), dim_order="ps", zscore=False)

    mi = MutualInfo(estimator="gaussian")
    je = JointEntropy(estimator="gaussian")

    bound = -0.5 * np.log(1 - 1 / (1 + GAUSSIAN_RIDGE) ** 2)
    direct = mi.multivariate(data)[0, 1]
    composed = (mi._compute_entropy(data, i=0) + mi._compute_entropy(data, i=1)
                - je.multivariate(data)[0, 1])

    assert direct == pytest.approx(bound, rel=1e-12)
    assert composed == pytest.approx(bound, abs=1e-7)
    assert je.bivariate(data, i=0, j=1) == pytest.approx(
        je.multivariate(data)[0, 1], abs=1e-7)


def test_gaussian_ridge_is_equivariant_to_per_variable_rescaling():
    """The ridge is proportional to each variable's own variance.

    An isotropic ridge eps = 1e-8 * mean(diag(Sigma)) makes the regularisation
    of a quiet variable depend on the units of a loud one, so `zscore=False`
    results move when an unrelated process is rescaled.
    """
    rng = np.random.default_rng(3)
    Z = rng.standard_normal((3, 500))
    Z[1] += 0.7 * Z[0]
    Z[2] += 0.5 * Z[1]

    mi = MutualInfo(estimator="gaussian")
    base = mi.multivariate(Data(data=Z, dim_order="ps", zscore=False))
    Z_scaled = Z.copy()
    Z_scaled[0] *= 1e6
    scaled = mi.multivariate(Data(data=Z_scaled, dim_order="ps", zscore=False))
    assert np.allclose(base, scaled, atol=1e-12, equal_nan=True)


# ---------------------------------------------------------------------------
# Transfer-entropy auto-embedding
# ---------------------------------------------------------------------------

def _ols_residual_variance(y, X):
    """Residual variance of an OLS fit with an intercept, computed directly."""
    design = np.column_stack([np.ones(len(y)), X]) if X.size else np.ones((len(y), 1))
    beta, *_ = np.linalg.lstsq(design, y, rcond=None)
    resid = y - design @ beta
    return float(resid @ resid / len(y))


def _lagged(series, dim, delay, end):
    """Columns [x_{t}, x_{t-delay}, ..., x_{t-(dim-1)delay}] ending at `end`."""
    start = (dim - 1) * delay
    return np.column_stack([series[start - i * delay: end - i * delay]
                            for i in range(dim)])


def _ols_ais(series, dim, delay):
    """Bias-corrected Gaussian AIS from OLS residual variances.

    Independent of pyspi's log-determinant machinery: AIS is
    0.5*log(var(Y) / var(Y | Y_past)), and each variance comes from an explicit
    least-squares fit. The k/(2N) correction is the mean of the chi-squared null
    of the in-sample estimate, the same term JIDT subtracts.
    """
    T = len(series)
    start, end = (dim - 1) * delay, T - 1
    if start >= end:
        return -np.inf
    future = series[start + 1: end + 1]
    past = _lagged(series, dim, delay, end)
    n = future.size
    return 0.5 * np.log(_ols_residual_variance(future, np.empty((n, 0)))
                        / _ols_residual_variance(future, past)) - dim / (2.0 * n)


def test_gaussian_ais_matches_an_ols_residual_variance_oracle():
    """Same quantity, assembled from least squares instead of log-determinants."""
    from pyspi.statistics.infotheory import _gaussian_ais

    rng = np.random.default_rng(0)
    T = 800
    x = np.zeros(T)
    for t in range(2, T):
        x[t] = 0.6 * x[t - 1] - 0.3 * x[t - 2] + rng.standard_normal()

    for dim in (1, 2, 3, 5):
        for delay in (1, 2):
            assert _gaussian_ais(x, dim, delay) == pytest.approx(
                _ols_ais(x, dim, delay), abs=1e-7), (dim, delay)


def test_embedding_search_is_a_brute_force_argmax_of_the_scorer():
    """Selection, separately from the criterion it maximises.

    Ties go to the smaller dimension and then the smaller delay -- the AIS
    objective plateaus often enough at finite sample that this matters. No
    assertion here that a particular AR order is recovered: it need not be.
    """
    from pyspi.statistics.infotheory import _select_embedding

    rng = np.random.default_rng(1)
    series = rng.standard_normal(400)
    scores = {}

    def scorer(_series, dim, delay):
        scores[(dim, delay)] = float(rng.standard_normal())
        return scores[(dim, delay)]

    dim, delay, score = _select_embedding(series, scorer, 5, 3)
    assert (dim, delay) == max(scores, key=lambda kd: (scores[kd], -kd[0], -kd[1]))
    assert score == scores[(dim, delay)]

    flat = _select_embedding(series, lambda *_: 1.0, 5, 3)
    assert flat[:2] == (1, 1), "a flat objective must not drift to the maximum"


def test_max_corr_ais_selects_source_and_destination_independently():
    """All four selected values must reach the estimator.

    `MAX_CORR_AIS` searched the destination only and hard-coded the source
    embedding to (1, 1), while its name denotes selection for both. An injected
    scorer that deliberately prefers different embeddings for the two series
    makes the difference observable.
    """
    import pyspi.statistics.infotheory as it

    rng = np.random.default_rng(2)
    src = rng.standard_normal(600)
    targ = rng.standard_normal(600)
    data = Data(data=np.vstack([src, targ]), dim_order="ps", zscore=False)

    # Scores the source's preferred embedding at (3, 2) and the destination's
    # at (2, 1); the two series are told apart by their first sample.
    def injected(_estimator, _k_nn=None, _w=0):
        def score(series, dim, delay):
            want = (3, 2) if series[0] == pytest.approx(data.to_numpy(
                squeeze=True)[0][0]) else (2, 1)
            return 1.0 if (dim, delay) == want else 0.0
        return score

    captured = {}
    real = it._gaussian_te_bivariate

    def spy(s, t, k_history, k_tau, l_history, l_tau):
        captured.update(k_history=k_history, k_tau=k_tau,
                        l_history=l_history, l_tau=l_tau)
        return real(s, t, k_history, k_tau, l_history, l_tau)

    spi = it.TransferEntropy(estimator="gaussian",
                             auto_embed_method="MAX_CORR_AIS",
                             k_search_max=4, tau_search_max=3)
    spi._embedding_scorer = staticmethod(injected)
    it._gaussian_te_bivariate = spy
    try:
        spi.bivariate(data, i=0, j=1)
    finally:
        it._gaussian_te_bivariate = real

    assert captured == {"k_history": 2, "k_tau": 1, "l_history": 3, "l_tau": 2}


def test_max_corr_ais_dest_only_keeps_the_supplied_source_embedding():
    import pyspi.statistics.infotheory as it

    rng = np.random.default_rng(3)
    data = Data(data=rng.standard_normal((2, 400)), dim_order="ps", zscore=False)

    captured = {}
    real = it._gaussian_te_bivariate

    def spy(s, t, k_history, k_tau, l_history, l_tau):
        captured.update(l_history=l_history, l_tau=l_tau)
        return real(s, t, k_history, k_tau, l_history, l_tau)

    spi = it.TransferEntropy(estimator="gaussian",
                             auto_embed_method="MAX_CORR_AIS_DEST_ONLY",
                             k_search_max=4, tau_search_max=2,
                             l_history=3, l_tau=2)
    it._gaussian_te_bivariate = spy
    try:
        spi.bivariate(data, i=0, j=1)
    finally:
        it._gaussian_te_bivariate = real
    assert captured == {"l_history": 3, "l_tau": 2}


def test_gaussian_transfer_entropy_matches_an_ols_oracle_at_a_fixed_embedding():
    """TE is the log ratio of two residual variances, so OLS gives it directly."""
    from pyspi.statistics.infotheory import _gaussian_te_bivariate

    rng = np.random.default_rng(4)
    T = 2000
    s = np.zeros(T)
    t = np.zeros(T)
    for n in range(3, T):
        s[n] = 0.7 * s[n - 1] + rng.standard_normal()
        t[n] = 0.4 * t[n - 1] + 0.5 * s[n - 2] + rng.standard_normal()

    k, k_tau, l, l_tau = 2, 1, 3, 1
    lookback = max((k - 1) * k_tau, l * l_tau)
    end = T - 1
    future = t[lookback + 1: end + 1]
    t_past = _lagged(t, k, k_tau, end)[-future.size:]
    s_past = np.column_stack([s[lookback - i * l_tau: end - i * l_tau]
                              for i in range(1, l + 1)])[-future.size:]

    expected = 0.5 * np.log(_ols_residual_variance(future, t_past)
                            / _ols_residual_variance(
                                future, np.column_stack([t_past, s_past])))
    got = _gaussian_te_bivariate(s, t, k, k_tau, l, l_tau)
    assert got == pytest.approx(expected, rel=2e-3), f"{got} vs {expected}"
